#11 - movimiento de sprites
Alemman/UnderworldLand pull request #12
Opened 2020-12-16 07:00 UTC by Alemman

se creo la clase hashMapSprite, Hero,Enemy y Floor; se crearon los metodos necesarios en Hero y Character, para mover los sprites por el mapa, la clase HashMapSprites se encarga de procesar los sprites

2020-12-17 04:09 UTC, iuresti commented on UnderWorldLand/Character.java
> +abstract public class Character extends Actor
Me gusta que tus métodos son pequeños y claros

2020-12-17 04:11 UTC, iuresti commented on UnderWorldLand/Character.java
> +        currentSprite = (++currentSprite) % hashMapSprites.arrayLength(keyDirection);
Muy bien usado el hash map

2020-12-17 04:18 UTC, iuresti requested changes

2020-12-17 04:18 UTC, iuresti commented on UnderWorldLand/HashMapSprite.java
> +    public int arrayLength(String key){
el nombre "arrayLength" indica que el usuario de la clase "HashMapSprite" conoce cómo está implementada la clase internamente.

Trata de separar el "Cómo interactúan otros con tu clase" de "Cómo está implementada internamente" ... el método se podría llamar "spritesCountByKey" por ejemplo ... el nombre es más claro en cuanto a qué significado tiene el entero que se regresa sin revelar los detalles internos de la implementación de la clase

2020-12-17 04:18 UTC, iuresti commented on UnderWorldLand/Hero.java
> +        GreenfootImage []spritesLeft = new GreenfootImage[6];
Es mucho más seguro utilizar un ArrayList en lugar de una array simple. También es más mantenible considerando que no tienes que especificar un tamaño inicial y puede crecer de ser necesario

2020-12-17 04:18 UTC, iuresti commented on UnderWorldLand/MapLoader.java
> +        for(int i = 0; i <= 400; i+=100){
Usa una constante con un nombre descriptivo para ese 100

2020-12-17 06:47 UTC, Alemman commented on UnderWorldLand/HashMapSprite.java
> +    public int arrayLength(String key){
Se cambio el nombre de metodo arrayLenght por spriteCountByKey

2020-12-17 06:48 UTC, Alemman commented on UnderWorldLand/Hero.java
> +        GreenfootImage []spritesLeft = new GreenfootImage[6];
se cambio el array por un arrayList

2020-12-17 06:48 UTC, Alemman commented on UnderWorldLand/MapLoader.java
> +        for(int i = 0; i <= 400; i+=100){
se puso una constante para el valor 100

2020-12-18 00:56 UTC, iuresti approved these changes

2020-12-18 01:45 UTC, merged