Branch aspectos finales 2
Alemman/UnderworldLand pull request #18
Opened 2020-12-21 19:49 UTC by Alemman

mostrar pantalla de fin de juego cuando se pierde y cuando se termina el juego guardar record

2020-12-28 22:38 UTC, iuresti requested changes

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/BtnSaveName.java
> +            userName += selectWord.getCurrentWord();
En Java los Strings son "inmutables" lo que significa que una vez creado no cambian su valor... cada vez que concatenas dos strings se genera un nuevo objeto para almacenar el valor. Por lo tanto, es una mala práctica utilizar concatenación dentro de ciclos. 

En lugar de usar String, se utiliza StringBuilder, en este caso es necesario que reescribas este ciclo por: 

```
StringBuilder userName = new StringBuilder();
for(SelectWord selectWord : list){
     userName.append(selectWord.getCurrentWord());
}
```
Para usar el valor almacenado en `userName`, deberás utilizar `userName.toString()`

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/GameOver.java
> +        while(musicCredits.isPlaying());
Este ciclo me parece que puede ser muy costoso en términos de uso de CPU, observa en tu sistema operativo si no sube el uso de procesador mientras se ejecuta este ciclo... para mejorarlo un `Greenfoot.delay(1)` dentro del ciclo podría ser suficiente.. o a lo mejor un `Thread.yield()` que causa que el hilo actual ceda el uso de CPU a los otros hilos en espera

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/Hero.java
> +           Hud hud = ((Map)getWorld()).getHud();
No olvides formatear tu código

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/SelectWord.java
> +        add("A");add("B");add("C");add("D");add("E");
no sabía que esto se podía jeje

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/SelectWord.java
> +        add("A");add("B");add("C");add("D");add("E");
también pudiste añadir un bloque estático con un ciclo:

```
static{
  for(char character = 'A'; character <= 'Z' ; character++){
      ALPHABET.add(String.valueOf(character));
  }

}
```

2020-12-28 22:38 UTC, iuresti commented on UnderWorldLand/SelectWord.java
> +            setImage(new GreenfootImage(ALPHABET.get(currentIndex), 45,  new Color(30, 130, 220, 180), new Color(27, 170, 255, 121), new Color(255, 255, 255, 255)));
La operación `ALPHABET.get(currentIndex)` al ser de un `LinkedList` tiene complejidad `O(n)` .. significa que cada vez que solicitas un índice, se recorrerá la lista desde el primer elemento hasta el n... 

Siendo este el uso que necesitas darle a tu lista, lo correcto es utilizar un ArrayList, que internamente tiene un arreglo simple y por lo tanto la complejidad es `O(1)` es decir, es constante

2020-12-29 00:51 UTC, Alemman commented on UnderWorldLand/BtnSaveName.java
> +            userName += selectWord.getCurrentWord();
se cambio string por stringBuilder

2020-12-29 00:52 UTC, Alemman commented on UnderWorldLand/GameOver.java
> +        while(musicCredits.isPlaying());
se agrego Thread.yield() a el ciclo

2020-12-29 00:52 UTC, Alemman commented on UnderWorldLand/Hero.java
> +           Hud hud = ((Map)getWorld()).getHud();
se formateo el codigo

2020-12-29 00:53 UTC, Alemman commented on UnderWorldLand/SelectWord.java
> +        add("A");add("B");add("C");add("D");add("E");
se agrego el bloque estatico sugerido

2020-12-29 00:54 UTC, Alemman commented on UnderWorldLand/SelectWord.java
> +            setImage(new GreenfootImage(ALPHABET.get(currentIndex), 45,  new Color(30, 130, 220, 180), new Color(27, 170, 255, 121), new Color(255, 255, 255, 255)));
se cambio el linkedList por un arrayList

2020-12-29 17:13 UTC, iuresti approved these changes

2020-12-30 00:04 UTC, merged