#6 - clase-record
Alemman/UnderworldLand pull request #8
Opened 2020-12-12 22:20 UTC by Alemman

se crearon los metodos para la clase record ahora se puede: guardar record y mostrarlo

2020-12-13 04:57 UTC, iuresti requested changes

2020-12-13 04:57 UTC, iuresti commented on UnderWorldLand/Record.java
> +            PrintWriter out = new PrintWriter(bw);
Este PrintWriter debe estar también dentro del try con recursos, recuerda que puedes poner múltiples sentencias separadas por punto y coma (también te recomiendo que sea una por línea aunque eso no es requerido)

2020-12-13 04:57 UTC, iuresti commented on UnderWorldLand/Record.java
> +            Scanner myReader = new Scanner(myObj);
Mete el escaner a un try con recursos

2020-12-13 04:57 UTC, iuresti commented on UnderWorldLand/myfile.txt
> +the text
Este archivo debe ser borrado de git y añadido al .gitignore

2020-12-13 04:57 UTC, iuresti commented on UnderWorldLand/Record.java
> +        Player mayor;
Me parece que players no debería ser parte del estado de la clase "Record" .. es más bien una variable local que se requiere en el contexto del método addRecord ... el método readRecords podría regresar esa variable en lugar de guardarla en el atributo.

Recuerda siempre utilizar el mínimo contexto posible.

2020-12-13 06:10 UTC, Alemman commented on UnderWorldLand/Record.java
> +            PrintWriter out = new PrintWriter(bw);
PrintWriter ya quedo dentro del try

2020-12-13 06:10 UTC, Alemman commented on UnderWorldLand/Record.java
> +            Scanner myReader = new Scanner(myObj);
scanner ya esta dentro de try

2020-12-13 06:11 UTC, Alemman commented on UnderWorldLand/myfile.txt
> +the text
se elimino el archivo myfile.txt

2020-12-13 06:13 UTC, Alemman commented on UnderWorldLand/Record.java
> +        Player mayor;
se elimino el arreglo players de los atributos y se agrego como locales en los metodos addRecord y readRecord

2020-12-13 20:17 UTC, iuresti commented on UnderWorldLand/Record.java
> +            while(current < players.length){
Se recomienda utilizar el for each para recorrer arreglos....
```
for(Player player: players){
}
```

2020-12-14 01:50 UTC, iuresti requested changes

2020-12-14 01:50 UTC, iuresti commented on UnderWorldLand/Record.java
> +            myReader.close();
Como el scanner está en el try con recursos, ya no es necesario cerrarlo

2020-12-14 08:09 UTC, Alemman commented on UnderWorldLand/Record.java
> +            myReader.close();
se elimino la linea myReader.close()
y se modifico el método addRecord ya que no cubría todos los casos de inserción

2020-12-14 09:07 UTC, iuresti approved these changes

2020-12-14 14:16 UTC, merged